### ISSUE TITLE
Is this project still actively maintained?

### ISSUE THREAD

**Issue by matthew-healy** [cloudsmith-io/gopack#1]
Hi folks!

I'm currently working on packaging a Go library which will be served from a private Cloudsmith repository. I made a fork of this repo ([matthew-healy/gopack](https://github.com/matthew-healy/gopack)) which adds a few new features I needed. Namely: the ability to pass a regex to use to filter the inputs to the `.zip`, and the ability to install the binary via `go install`.

I'd be happy to open a PR to upstream my changes, but I'm also happy to maintain my fork if this project has been abandoned.

**Comment by paddycarey** [comment]
Hey @matthew-healy, thanks for the note. We're very happy to accept changes or improvements here. There haven't been many updates recently, but that's mostly because the existing featureset is so small and it does what we needed.

If you want to submit I can make sure it gets reviewed by the right people (though it may take a couple days).

**Comment by matthew-healy** [comment]
Awesome, thanks for the quick reply @paddycarey! I'll tidy up my changes & submit a PR later today.
